language: java
os: linux
dist: bionic
arch: amd64
jdk:
  - openjdk11

cache:
  bundler: false
  cargo: false
  directories:
    - '$HOME/.m2'

addons:
  sonarcloud:
    organization: fabianoveglianti
    token: 70b0ab8fe899f3caf35bbb4557356b3cd70c1a74

git:
  depth: 2

env:
  global:
  - MAVEN_OPTS="-Xmx4096M -Xss128M -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -noverify"
  - DBMS=H2
  - jaxrsContentType=application/json
  - TestCommand="mvn -U -T 1C clean test -Dinvoker.streamLogs=true -Dmodernizer.skip=true -Dianal.skip=true -Drat.skip=true -Dcheckstyle.skip=true -Dsass.skip=true"
before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh -O ~/install-jdk.sh && chmod +x ~/install-jdk.sh
install: mvn install -DSkipTests=true -Dmaven.javadoc.skip=true -B -V -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dhttps-protocols=TLSv1,TLSv1.1,TLSv1.2
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn -Dtest=MyEncryptorTest,MyRealmValidatorTest -DfailIfNoTests=false clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=FabianoVeglianti_syncope





